# Generated by Django 5.2.6 on 2025-09-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_document_confidence_scores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namedentity',
            name='document',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='employee_id',
        ),
        migrations.DeleteModel(
            name='DocumentNotification',
        ),
        migrations.DeleteModel(
            name='NamedEntity',
        ),
    ]
